# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('score', models.FloatField(default=0)),
                ('task_id', models.IntegerField(default=0)),
                ('poster_user_id', models.IntegerField(default=0)),
                ('postee_user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
